name: Run tests

on:
  push:

jobs:
  format:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Run prettier
      run: npm run format

    - name: Commit changes
      run: "git commit --allow-empty -m 'Run prettier'"

    - name: Push changes
      run: git push
